create table membership_plan (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    description varchar(255) not null,
    duration varchar(20) not null check (duration in ('MONTHLY', 'QUARTERLY', 'YEARLY')),
    status varchar(20) not null check (status in ('ACTIVE', 'INACTIVE')),
    price numeric(12, 2) not null,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table membership_tier (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    type varchar(20) not null unique check (type in ('SILVER', 'GOLD', 'PLATINUM')),
    description varchar(255) not null,
    status varchar(20) not null check (status in ('ACTIVE', 'INACTIVE')),
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table membership_tier_rules (
    id bigint generated by default as identity primary key,
    membership_tier_id bigint not null references membership_tier(id),
    cohorts json not null,
    min_order_value numeric(12, 2),
    min_order_count integer,
    status varchar(20) not null check (status in ('ACTIVE', 'INACTIVE')),
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table user_membership (
    id bigint generated by default as identity primary key,
    user_id varchar(100) not null,
    membership_plan_id bigint not null references membership_plan(id),
    membership_tier_id bigint not null references membership_tier(id),
    start_at timestamp with time zone not null,
    end_at timestamp with time zone not null,
    cancelled_at timestamp with time zone,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp
);

create table user_monthly_orders_meta (
    id bigint generated by default as identity primary key,
    user_id varchar(100) not null,
    year integer not null,
    month integer not null,
    total_orders integer not null default 0,
    total_order_value numeric(12, 2) not null default 0,
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint uk_user_monthly_orders_meta_user_year_month unique (user_id, year, month)
);

create index idx_membership_plan_status on membership_plan(status);
create index idx_membership_tier_status on membership_tier(status);
create index idx_membership_tier_rules_status on membership_tier_rules(status);
create index idx_membership_tier_rules_tier_id on membership_tier_rules(membership_tier_id);
create index idx_user_membership_user_active on user_membership(user_id, cancelled_at, end_at);
create index idx_user_monthly_orders_meta_user on user_monthly_orders_meta(user_id);
